// Built-in named preset templates for users to load as starting points
// These are read-only and not modifiable by users
import type { Preset } from '../types/AppContext.types';

export const BUILT_IN_PRESETS: Preset[] = [
  {
    name: 'Early Pre-Seed (idea stage)',
    capital: 50000,
    burn: 5000,
    revenue: 0,
    growth: 0,
    headcount: 1,
    cac: 0,
    arpu: 0,
    churn: 0,
    pipeline: 0,
    companyName: 'My Startup',
    idea: 'Describe your startup idea here',
    industry: 'B2B SaaS',
    problem: 'The core problem you are solving',
    stage: 'Pre-Seed',
    founder: 'Founder Name',
    northStar: 'Get to first paying customer',
    valuation: 500000,
    targetRaise: 150000,
    dilution: 15,
    grossMargin: 80,
    ndr: 100,
    magicNumber: 0,
    teamSize: 1,
    productDescription: 'Describe your product',
    targetCustomer: 'Early adopters',
    competitors: 'Existing solutions in the space',
    traction: 'Waitlist / prototype / user interviews',
    useOfFunds: '100% product development',
    solutionStatement: 'Describe your solution',
    uniqueInsight: 'The non-obvious insight that drives your approach',
    founderBios: 'Founder background and why you are building this',
    tam: 1000000000,
    sam: 100000000,
    som: 5000000,
    revenueModel: 'SaaS',
  },
  {
    name: 'Pre-Seed (first product, no revenue)',
    capital: 150000,
    burn: 10000,
    revenue: 0,
    growth: 0,
    headcount: 2,
    cac: 500,
    arpu: 200,
    churn: 3,
    pipeline: 50000,
    companyName: 'My Startup',
    idea: 'First product shipped, seeking product-market fit',
    industry: 'B2B SaaS',
    problem: 'Problem your first customers experience',
    stage: 'Pre-Seed',
    founder: 'Founder Name',
    northStar: 'Reach $10K MRR from 50 customers',
    valuation: 1500000,
    targetRaise: 500000,
    dilution: 20,
    grossMargin: 75,
    ndr: 100,
    magicNumber: 0.5,
    teamSize: 2,
    productDescription: 'V1 product shipped to beta users',
    targetCustomer: 'SMBs in target vertical',
    competitors: 'Incumbents + point solutions',
    traction: '10 beta users, positive feedback, 0 paying yet',
    useOfFunds: '60% engineering, 30% sales, 10% ops',
    solutionStatement: 'Your solution statement',
    uniqueInsight: 'Your unfair advantage',
    founderBios: 'Technical + domain expertise on founding team',
    tam: 5000000000,
    sam: 500000000,
    som: 25000000,
    revenueModel: 'SaaS',
  },
  {
    name: 'Seed (early revenue, raising $1-3M)',
    capital: 400000,
    burn: 35000,
    revenue: 15000,
    growth: 12,
    headcount: 5,
    cac: 800,
    arpu: 300,
    churn: 2,
    pipeline: 300000,
    companyName: 'My Startup',
    idea: 'Proven product with early revenue traction',
    industry: 'B2B SaaS',
    problem: 'Validated problem with paying customers',
    stage: 'Seed',
    founder: 'Founder Name',
    northStar: 'Reach $1M ARR within 18 months',
    valuation: 6000000,
    targetRaise: 2000000,
    dilution: 18,
    grossMargin: 78,
    ndr: 108,
    magicNumber: 0.75,
    teamSize: 5,
    productDescription: 'Core product with proven retention',
    targetCustomer: 'Mid-market B2B companies',
    competitors: 'Category leaders + emerging competitors',
    traction: '$15K MRR · 50 paying customers · 12% MoM growth · NPS 55',
    useOfFunds: '50% engineering, 30% GTM, 20% ops',
    solutionStatement: 'Your validated solution',
    uniqueInsight: 'Data/distribution moat that incumbents cannot replicate',
    founderBios: 'Domain expert + operator, previously scaled similar business',
    tam: 10000000000,
    sam: 1000000000,
    som: 50000000,
    revenueModel: 'SaaS',
  },
];
